server {
    listen 80;

    # Odesílání statických souborů z React buildu
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Podpora pro React Router (Single Page Application)
    # Když klient požádá o /foods, Nginx zkusí najít složku nebo soubor.
    # Pokud neexistuje, vrátí index.html a nechá React Router, ať to vyřeší.
    # Bezpečnostní hlavičky + povolení kamery pro PWA
    add_header Permissions-Policy "camera=*, microphone=()" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy pro backend API (Nginx)
    location /api/ {
        # Přesměruje požadavky z /api/foods na http://backend:8000/foods
        # Podobně jako lokální vite.config.ts rewrite
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
