"""Add food portion

Revision ID: 887fd7d5ca83
Revises: ee901c22dca6
Create Date: 2026-07-05 11:15:04.353506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887fd7d5ca83'
down_revision: Union[str, Sequence[str], None] = 'ee901c22dca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_meal_log_portion_id_food_portions'), 'food_portions', ['portion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meal_log_portion_id_food_portions'), type_='foreignkey')

    # ### end Alembic commands ###
