"""feat: add recipe portion to meal log

Revision ID: afc6cf09e76b
Revises: fa8fc9cda9ff
Create Date: 2026-07-08 08:34:24.026439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc6cf09e76b'
down_revision: Union[str, Sequence[str], None] = 'fa8fc9cda9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_portion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_meal_log_recipe_portion_id_recipe_portions'), 'recipe_portions', ['recipe_portion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meal_log_recipe_portion_id_recipe_portions'), type_='foreignkey')
        batch_op.drop_column('recipe_portion_id')

    # ### end Alembic commands ###
