"""feat: add macros and portions to Recipe

Revision ID: fa8fc9cda9ff
Revises: fb4ef97f58c3
Create Date: 2026-07-06 12:28:35.161651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8fc9cda9ff'
down_revision: Union[str, Sequence[str], None] = 'fb4ef97f58c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_portions_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_portions'))
    )
    with op.batch_alter_table('recipe_portions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_portions_id'), ['id'], unique=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_100g', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fat_per_100g', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('saturates_per_100g', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('carbs_per_100g', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sugar_per_100g', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('protein_per_100g', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('salt_per_100g', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('salt_per_100g')
        batch_op.drop_column('protein_per_100g')
        batch_op.drop_column('sugar_per_100g')
        batch_op.drop_column('carbs_per_100g')
        batch_op.drop_column('saturates_per_100g')
        batch_op.drop_column('fat_per_100g')
        batch_op.drop_column('calories_per_100g')

    with op.batch_alter_table('recipe_portions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_portions_id'))

    op.drop_table('recipe_portions')
    # ### end Alembic commands ###
