"""Add is_deleted to Food

Revision ID: fb4ef97f58c3
Revises: 887fd7d5ca83
Create Date: 2026-07-05 18:02:51.553110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4ef97f58c3'
down_revision: Union[str, Sequence[str], None] = '887fd7d5ca83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name=op.f('fk_food_portions_food_id_food')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_portions'))
    )
    with op.batch_alter_table('food_portions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_portions_id'), ['id'], unique=False)

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_meal_log_portion_id_food_portions'), 'food_portions', ['portion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meal_log_portion_id_food_portions'), type_='foreignkey')
        batch_op.drop_column('portion_id')

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('food_portions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_portions_id'))

    op.drop_table('food_portions')
    # ### end Alembic commands ###
